on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and redeploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PUBLICIP }}
          username: ubuntu
          key: ${{ secrets.LABSUSERPEM }}
          script: |
            cd trigo_cicd
            chmod +x redeploy.sh
            ./redeploy.sh
